apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-art-explainer-28
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-art-explainer-28
    app.kubernetes.io/part-of: kserve-art-explainer
  name: kserve-art-explainer-28
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-art-explainer-28
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-art-explainer-28
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-art-explainer/kserve-art-explainer-28@sha256:abefc514dcfa6b3977f50cb0f9d9f795bb9a7afdc94d5498616223ab11ef9cca
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
